import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Page.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
		<link rel='manifest' href='/manifest.json' />
      </Head>

      <main className={styles.main}>
	  <ul className={styles.menu}>
			  <li><Link href="/">Domů</Link></li>
			  <li><Link href="/about">O nás</Link></li>
			</ul>
        <h1 className={styles.title}>
          Stopwatch
        </h1>

        <p className={styles.description}>
         Zde bude počítadlo
        </p>
      </main>
    </div>
  )
}
